name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker buildx build -t ${{ env.DOCKER_IMAGE_NAME }} .

    - name: Save Docker Image as Tar
      run: docker save -o image.tar ${{ env.DOCKER_IMAGE_NAME }}

    - name: Copy Docker Image to SSH Server
      uses: appleboy/scp-action@master
      with:
        host: $secrets.SERVER_IP
        username: ${{secrets.SSH_USER}}
        key: ${{secrets.SSH_PRIVATE_KEY}}
        source: ./image.tar
        target: ~/image.tar
    - name: Load Docker Image on SSH Server and Run
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.SERVER_IP}}
        username: $secrets.SSH_USER
        key: ${{secrets.SSH_PRIVATE_KEY}}
        script: |
          docker load -i ~/image.tar
          docker stop ${{env.DOCKER_IMAGE_NAME}} || true
          docker rm ${{env.DOCKER_IMAGE_NAME}} || true
          docker run -d -p 8000:8000 --name ${{env.DOCKER_IMAGE_NAME}} -e TOKEN=${{secrets.DISCORD_BOT_TOKEN}} -v ~/db:/db ${{env.DOCKER_IMAGE_NAME}}